# This rule is not used by the project autopeer-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to autopeer.badaimweeb.me resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autopeer-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodes-viewer-role
rules:
- apiGroups:
  - autopeer.badaimweeb.me
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autopeer.badaimweeb.me
  resources:
  - nodes/status
  verbs:
  - get
