name: Build Job Worker

on:
  push:
    paths:
      - 'job-worker/**'
      - '.github/workflows/build-job-worker.yml'
    tags:
      - "v[0-9]+.[0-9]+.*"

jobs:
  publish:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set RELEASE_VERSION env var
        id: set_version
        run: |
          if [[ "${{ startsWith(inputs.ref, 'refs/tags/v') }}" == "true" ]]; then
            RELEASE_VERSION=$(echo -n ${{ inputs.ref }} | cut -d '/' -f 3)
          else
            RELEASE_VERSION=$(date +%Y%m%d-%H%M%S)-g$(git rev-parse --short HEAD)
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository name & get commit SHA
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Build and push job-worker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/job-worker:${{ env.RELEASE_VERSION }}
          context: job-worker
          platforms: linux/amd64,linux/arm64
